char table_create_Myrank[] = "\
CREATE TABLE IF NOT EXISTS Myrank ( \
    SteamID32 INTEGER UNSIGNED NOT NULL, \
    Score INTEGER UNSIGNED NOT NULL DEFAULT 0, \
    LastUpdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, \
    CONSTRAINT PK_Player PRIMARY KEY (SteamID32))";
